// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/cashflow/analytics/monthly": {
            "get": {
                "description": "Returns monthly incoming, outgoing and net totals for the selected range.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transactions"
                ],
                "summary": "Get cashflow monthly analytics",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Start date (YYYY-MM-DD)",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End date (YYYY-MM-DD)",
                        "name": "to",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Include ignored transactions",
                        "name": "include_ignored",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.CashflowMonthlyAnalyticsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/cashflow/analytics/tags": {
            "get": {
                "description": "Returns tag distribution for combined, incoming and outgoing transactions in the selected range.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transactions"
                ],
                "summary": "Get cashflow tag distribution",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Start date (YYYY-MM-DD)",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End date (YYYY-MM-DD)",
                        "name": "to",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Include ignored transactions",
                        "name": "include_ignored",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.CashflowTagDistributionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/cashflow/transactions": {
            "get": {
                "description": "Filter cashflow transactions with explicit field filters and optional fuzzy search over description, note, and tag.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transactions"
                ],
                "summary": "Search cashflow transactions",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page size",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Offset",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort field: date, description, note, tag, source, amount",
                        "name": "sort_by",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort order: asc or desc",
                        "name": "sort_order",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Fuzzy query over description, note, tag",
                        "name": "q",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Case-insensitive contains filter on description",
                        "name": "description",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Case-insensitive contains filter on note",
                        "name": "note",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Case-insensitive contains filter on source",
                        "name": "source",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Direction filter: in or out",
                        "name": "direction",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Comma-separated tags, e.g. food,travel",
                        "name": "tags",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Only untagged transactions (empty tag)",
                        "name": "untagged",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Hide ignored transactions",
                        "name": "hide_ignored",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Start date (YYYY-MM-DD)",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End date (YYYY-MM-DD)",
                        "name": "to",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.CashflowTransactionsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/cashflow/transactions/ignore/filter": {
            "post": {
                "description": "Set ignored=true/false for all transactions that match the supplied filter.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transactions"
                ],
                "summary": "Ignore filtered cashflow transactions",
                "parameters": [
                    {
                        "description": "Filter ignore request",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.IgnoreTransactionsByFilterRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.TagTransactionsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/cashflow/transactions/ignore/selection": {
            "post": {
                "description": "Set ignored=true/false for selected transaction IDs.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transactions"
                ],
                "summary": "Ignore selected cashflow transactions",
                "parameters": [
                    {
                        "description": "Selection ignore request",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.IgnoreTransactionsBySelectionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.TagTransactionsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/cashflow/transactions/tag": {
            "post": {
                "description": "Apply a tag to a transaction by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transactions"
                ],
                "summary": "Tag a transaction",
                "parameters": [
                    {
                        "description": "Tag request",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.TagTransactionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/cashflow/transactions/tag/filter": {
            "post": {
                "description": "Apply/overwrite tag for all transactions that match the supplied filter.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transactions"
                ],
                "summary": "Tag filtered cashflow transactions",
                "parameters": [
                    {
                        "description": "Filter tag request",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.TagTransactionsByFilterRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.TagTransactionsResponse"
                        }
                    },
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/api.TagTransactionsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/cashflow/transactions/tag/selection": {
            "post": {
                "description": "Apply/overwrite tag for selected transaction IDs.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transactions"
                ],
                "summary": "Tag selected cashflow transactions",
                "parameters": [
                    {
                        "description": "Selection tag request",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.TagTransactionsBySelectionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.TagTransactionsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/dailies": {
            "get": {
                "description": "Get daily market data for a symbol with optional date range and pagination",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dailies"
                ],
                "summary": "Fetch daily market data",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Listing symbol (e.g. TDT.AS)",
                        "name": "symbol",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Start date (YYYY-MM-DD)",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End date (YYYY-MM-DD)",
                        "name": "to",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page size",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Offset",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/marketdata.DailyResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Returns 200 when service is healthy",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "status",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/import/csv": {
            "post": {
                "description": "Upload a CSV file containing transaction data to import into a specific vendor",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "imports"
                ],
                "summary": "Import transactions from CSV file",
                "parameters": [
                    {
                        "type": "file",
                        "description": "CSV file containing transaction data",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "UUID of the vendor to import transactions for",
                        "name": "vendor_id",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Import ID of the created import job",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Invalid request (missing file, invalid vendor_id, etc.)",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "413": {
                        "description": "File too large (max 20MB)",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "415": {
                        "description": "Unsupported media type (only text/csv allowed)",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.CashflowMonthlyAnalyticsPoint": {
            "type": "object",
            "properties": {
                "incomingCents": {
                    "type": "integer",
                    "example": 250000
                },
                "month": {
                    "type": "string",
                    "example": "2025-01-01"
                },
                "netCents": {
                    "type": "integer",
                    "example": 130000
                },
                "outgoingCents": {
                    "type": "integer",
                    "example": 120000
                }
            }
        },
        "api.CashflowMonthlyAnalyticsResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.CashflowMonthlyAnalyticsPoint"
                    }
                }
            }
        },
        "api.CashflowTagDistributionEntry": {
            "type": "object",
            "properties": {
                "tag": {
                    "type": "string",
                    "example": "food"
                },
                "totalCents": {
                    "type": "integer",
                    "example": 4200
                }
            }
        },
        "api.CashflowTagDistributionResponse": {
            "type": "object",
            "properties": {
                "combined": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.CashflowTagDistributionEntry"
                    }
                },
                "incoming": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.CashflowTagDistributionEntry"
                    }
                },
                "outgoing": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.CashflowTagDistributionEntry"
                    }
                }
            }
        },
        "api.CashflowTagFilters": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "direction": {
                    "type": "string"
                },
                "from": {
                    "type": "string"
                },
                "hide_ignored": {
                    "type": "boolean"
                },
                "note": {
                    "type": "string"
                },
                "q": {
                    "type": "string"
                },
                "source": {
                    "type": "string"
                },
                "tags": {
                    "type": "string"
                },
                "to": {
                    "type": "string"
                },
                "untagged": {
                    "type": "boolean"
                }
            }
        },
        "api.CashflowTransactionsResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.Transaction"
                    }
                },
                "pagination": {
                    "$ref": "#/definitions/api.Pagination"
                }
            }
        },
        "api.IgnoreTransactionsByFilterRequest": {
            "type": "object",
            "properties": {
                "filters": {
                    "$ref": "#/definitions/api.CashflowTagFilters"
                },
                "ignored": {
                    "type": "boolean"
                }
            }
        },
        "api.IgnoreTransactionsBySelectionRequest": {
            "type": "object",
            "properties": {
                "ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "ignored": {
                    "type": "boolean"
                }
            }
        },
        "api.Pagination": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "limit": {
                    "type": "integer"
                },
                "offset": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "api.TagTransactionRequest": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "tag": {
                    "type": "string"
                }
            }
        },
        "api.TagTransactionsByFilterRequest": {
            "type": "object",
            "properties": {
                "filters": {
                    "$ref": "#/definitions/api.CashflowTagFilters"
                },
                "tag": {
                    "type": "string"
                }
            }
        },
        "api.TagTransactionsBySelectionRequest": {
            "type": "object",
            "properties": {
                "ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "tag": {
                    "type": "string"
                }
            }
        },
        "api.TagTransactionsResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string"
                },
                "updated_count": {
                    "type": "integer"
                }
            }
        },
        "api.Transaction": {
            "type": "object",
            "properties": {
                "amountCents": {
                    "type": "integer",
                    "example": 4250
                },
                "date": {
                    "type": "string",
                    "example": "2025-01-15T00:00:00Z"
                },
                "description": {
                    "type": "string",
                    "example": "Grocery shopping"
                },
                "direction": {
                    "type": "string",
                    "example": "out"
                },
                "id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "ignored": {
                    "type": "boolean",
                    "example": false
                },
                "note": {
                    "type": "string",
                    "example": "Bought fruits and vegetables"
                },
                "source": {
                    "type": "string",
                    "example": "MyBank"
                },
                "tag": {
                    "type": "string",
                    "example": "Food"
                }
            }
        },
        "marketdata.Daily": {
            "type": "object",
            "properties": {
                "close": {
                    "type": "integer"
                },
                "createdAt": {
                    "type": "string"
                },
                "date": {
                    "type": "string"
                },
                "high": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "low": {
                    "type": "integer"
                },
                "open": {
                    "type": "integer"
                },
                "symbol": {
                    "description": "This is used to link back to the listing, e.g. \"AAPL\"",
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "volume": {
                    "type": "integer"
                }
            }
        },
        "marketdata.DailyResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/marketdata.Daily"
                    }
                },
                "metadata": {
                    "$ref": "#/definitions/marketdata.Metadata"
                }
            }
        },
        "marketdata.Metadata": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "resultCount": {
                    "type": "integer"
                },
                "totalCount": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
